import { Shop, Review, Notice, QnA, User } from './types';

// ===== 모의 사용자 데이터 =====
export const MOCK_USERS: User[] = [
  {
    id: 'admin',
    email: 'admin@healing.com',
    name: '최고관리자',
    role: 'ADMIN',
    status: 'approved',
  },
  {
    id: 'user-shop-001',
    email: 'owner1@healing.com',
    name: '강남스파사장님',
    role: 'OWNER',
    managedShopId: 'shop-001',
    status: 'approved',
    businessName: '강남힐링스파',
    businessNumber: '123-45-67890',
    phone: '010-1111-2222'
  },
  {
    id: 'user-shop-002',
    email: 'owner2@healing.com',
    name: '홍대아로마사장님',
    role: 'OWNER',
    managedShopId: 'shop-002',
    status: 'approved',
    businessName: '홍대아로마',
    businessNumber: '234-56-78901',
    phone: '010-2222-3333'
  },
  {
    id: 'user-pending-1',
    email: 'newowner@spa.com',
    name: '대기입점사',
    role: 'OWNER',
    status: 'pending',
    businessName: '신규테라피',
    businessNumber: '999-88-77777',
    phone: '010-9999-8888'
  }
];

// ===== 목업 업소 데이터 =====
export const MOCK_SHOPS: Shop[] = [
  // 프리미엄 업소 3개
  {
    id: 'shop-001',
    name: '강남 힐링스파',
    slug: 'gangnam-healing-spa',
    region: 'seoul',
    regionLabel: '서울',
    subRegion: 'gangnam',
    subRegionLabel: '강남구',
    theme: 'swedish',
    themeLabel: '스웨디시',
    isPremium: true,
    premiumOrder: 1,
    thumbnailUrl: '/images/shop1-thumb.jpg',
    bannerUrl: '/images/shop1-banner.jpg',
    images: ['/images/shop1-1.jpg', '/images/shop1-2.jpg'],
    tagline: '강남 최고의 프리미엄 스웨디시 마사지',
    description: '강남 중심부에 위치한 힐링스파는 10년 이상의 노하우를 가진 전문 테라피스트가 최상의 서비스를 제공합니다. 모든 오일은 천연 성분만을 사용하며, 쾌적하고 청결한 환경을 자랑합니다.',
    address: '서울특별시 강남구 테헤란로 123',
    phone: '010-1234-5678',
    hours: '매일 10:00 - 23:00',
    rating: 4.8,
    reviewCount: 128,
    courses: [
      { name: '베이직 스웨디시', duration: '60분', price: '70,000원', description: '전신 릴렉스 코스' },
      { name: '프리미엄 스웨디시', duration: '90분', price: '100,000원', description: '딥 릴렉스 + 아로마' },
      { name: '로얄 케어', duration: '120분', price: '140,000원', description: '전신 + 두피 + 발 집중 코스' },
    ],
    tags: ['주차가능', '예약우대', '카드결제', '여성전용관'],
    isVisible: true,
    ownerId: 'user-shop-001',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'shop-002',
    name: '홍대 아로마테라피',
    slug: 'hongdae-aromatherapy',
    region: 'seoul',
    regionLabel: '서울',
    subRegion: 'mapo',
    subRegionLabel: '마포구',
    theme: 'aroma',
    themeLabel: '아로마',
    isPremium: true,
    premiumOrder: 2,
    thumbnailUrl: '/images/shop2-thumb.jpg',
    bannerUrl: '/images/shop2-banner.jpg',
    images: ['/images/shop2-1.jpg'],
    tagline: '홍대 감성 힐링 아로마 테라피',
    description: '홍대 감성이 가득한 프라이빗한 공간에서 최고급 에센셜 오일로 몸과 마음의 균형을 회복하세요. 1:1 맞춤 케어 서비스를 제공합니다.',
    address: '서울특별시 마포구 와우산로 45',
    phone: '010-2345-6789',
    hours: '평일 11:00 - 22:00 / 주말 10:00 - 23:00',
    rating: 4.7,
    reviewCount: 95,
    courses: [
      { name: '아로마 릴렉스', duration: '60분', price: '65,000원' },
      { name: '아로마 딥케어', duration: '90분', price: '95,000원' },
    ],
    tags: ['프라이빗룸', '여성전용', '카드결제'],
    isVisible: true,
    ownerId: 'user-shop-002',
    createdAt: '2024-02-01',
    updatedAt: '2024-06-02',
  },
  {
    id: 'shop-003',
    name: '부산 타이마사지',
    slug: 'busan-thai-massage',
    region: 'busan',
    regionLabel: '부산',
    subRegion: 'haeundae',
    subRegionLabel: '해운대구',
    theme: 'thai',
    themeLabel: '타이',
    isPremium: true,
    premiumOrder: 3,
    thumbnailUrl: '/images/shop3-thumb.jpg',
    bannerUrl: '/images/shop3-banner.jpg',
    images: ['/images/shop3-1.jpg'],
    tagline: '정통 타이 마사지 부산 1위',
    description: '태국 치앙마이에서 직접 연수받은 정통 타이 마사지 전문점. 유연성 향상과 근육 이완에 탁월한 효과를 제공합니다.',
    address: '부산광역시 해운대구 해운대로 200',
    phone: '010-3456-7890',
    hours: '매일 09:00 - 24:00',
    rating: 4.9,
    reviewCount: 210,
    courses: [
      { name: '타이 기본', duration: '60분', price: '55,000원' },
      { name: '타이 풀코스', duration: '120분', price: '100,000원' },
    ],
    tags: ['정통타이', '주차가능', '남녀모두'],
    isVisible: true,
    ownerId: 'user-shop-003',
    createdAt: '2024-01-15',
    updatedAt: '2024-06-03',
  },
  // 일반 업소
  {
    id: 'shop-004',
    name: '수원 스포츠마사지',
    slug: 'suwon-sports-massage',
    region: 'gyeonggi',
    regionLabel: '경기',
    subRegion: 'suwon',
    subRegionLabel: '수원시',
    theme: 'sport',
    themeLabel: '스포츠',
    isPremium: false,
    thumbnailUrl: '/images/shop4-thumb.jpg',
    bannerUrl: '/images/shop4-banner.jpg',
    images: [],
    tagline: '운동 후 완벽한 회복, 스포츠 마사지',
    description: '스포츠 재활 전문가가 운영하는 스포츠 마사지 전문점입니다.',
    address: '경기도 수원시 영통구 봉영로 88',
    phone: '010-4567-8901',
    hours: '평일 09:00 - 21:00 / 주말 10:00 - 20:00',
    rating: 4.5,
    reviewCount: 67,
    courses: [
      { name: '스포츠 기본', duration: '60분', price: '60,000원' },
      { name: '스포츠 집중', duration: '90분', price: '85,000원' },
    ],
    tags: ['재활전문', '남녀모두', '카드결제'],
    isVisible: true,
    createdAt: '2024-03-01',
    updatedAt: '2024-06-04',
  },
  {
    id: 'shop-005',
    name: '인천 딥티슈 센터',
    slug: 'incheon-deep-tissue',
    region: 'incheon',
    regionLabel: '인천',
    subRegion: 'namdong',
    subRegionLabel: '남동구(구월)',
    theme: 'deep',
    themeLabel: '딥티슈',
    isPremium: false,
    thumbnailUrl: '/images/shop5-thumb.jpg',
    bannerUrl: '/images/shop5-banner.jpg',
    images: [],
    tagline: '만성 근육통 해소의 정답',
    description: '딥티슈 전문 테라피스트가 만성 근육통과 결림을 해소해드립니다.',
    address: '인천광역시 남동구 구월로 112',
    phone: '010-5678-9012',
    hours: '매일 10:00 - 22:00',
    rating: 4.6,
    reviewCount: 83,
    courses: [
      { name: '딥티슈 기본', duration: '60분', price: '65,000원' },
      { name: '딥티슈 집중', duration: '90분', price: '90,000원' },
    ],
    tags: ['만성통증', '남녀모두'],
    isVisible: true,
    createdAt: '2024-03-15',
    updatedAt: '2024-06-05',
  },
  {
    id: 'shop-006',
    name: '대전 핫스톤 힐링',
    slug: 'daejeon-hot-stone',
    region: 'daejeon',
    regionLabel: '대전',
    subRegion: '',
    subRegionLabel: '',
    theme: 'hot_stone',
    themeLabel: '핫스톤',
    isPremium: false,
    thumbnailUrl: '/images/shop6-thumb.jpg',
    bannerUrl: '/images/shop6-banner.jpg',
    images: [],
    tagline: '따뜻한 돌의 기운으로 깊은 힐링',
    description: '현무암 핫스톤과 아로마 오일이 어우러진 프리미엄 힐링 경험',
    address: '대전광역시 서구 둔산로 77',
    phone: '010-6789-0123',
    hours: '평일 11:00 - 22:00',
    rating: 4.7,
    reviewCount: 54,
    courses: [
      { name: '핫스톤 기본', duration: '70분', price: '75,000원' },
      { name: '핫스톤 풀코스', duration: '100분', price: '110,000원' },
    ],
    tags: ['핫스톤', '여성전용', '예약필수'],
    isVisible: true,
    createdAt: '2024-04-01',
    updatedAt: '2024-06-06',
  },
  {
    id: 'shop-007',
    name: '제주 쉼표 마사지',
    slug: 'jeju-rest-massage',
    region: 'jeju',
    regionLabel: '제주',
    subRegion: '',
    subRegionLabel: '',
    theme: 'aroma',
    themeLabel: '아로마',
    isPremium: false,
    thumbnailUrl: '/images/shop7-thumb.jpg',
    bannerUrl: '/images/shop7-banner.jpg',
    images: [],
    tagline: '제주 자연을 담은 아로마 힐링',
    description: '제주 여행 중 완벽한 휴식을 찾는다면 쉼표 마사지로 오세요.',
    address: '제주특별자치도 제주시 연동 444',
    phone: '010-7890-1234',
    hours: '매일 10:00 - 23:00',
    rating: 4.8,
    reviewCount: 137,
    courses: [
      { name: '제주 아로마', duration: '60분', price: '60,000원' },
      { name: '제주 커플 패키지', duration: '90분', price: '110,000원 (2인)' },
    ],
    tags: ['커플가능', '제주산오일', '뷰맛집'],
    isVisible: true,
    createdAt: '2024-04-15',
    updatedAt: '2024-06-07',
  },
  {
    id: 'shop-008',
    name: '강남 발마사지 천국',
    slug: 'gangnam-foot-massage',
    region: 'seoul',
    regionLabel: '서울',
    subRegion: 'gangnam',
    subRegionLabel: '강남구',
    theme: 'foot',
    themeLabel: '발마사지',
    isPremium: false,
    thumbnailUrl: '/images/shop8-thumb.jpg',
    bannerUrl: '/images/shop8-banner.jpg',
    images: [],
    tagline: '하루 종일 걸은 당신의 발을 위해',
    description: '발 반사 요법 전문가가 운영하는 발마사지 전문점. 피로 회복과 혈액순환 개선에 탁월합니다.',
    address: '서울특별시 강남구 역삼로 88',
    phone: '010-8901-2345',
    hours: '매일 11:00 - 24:00',
    rating: 4.5,
    reviewCount: 92,
    courses: [
      { name: '발 기본', duration: '40분', price: '35,000원' },
      { name: '발 + 종아리', duration: '60분', price: '50,000원' },
      { name: '전신 + 발', duration: '90분', price: '80,000원' },
    ],
    tags: ['당일예약가능', '남녀모두', '카드결제'],
    isVisible: true,
    createdAt: '2024-05-01',
    updatedAt: '2024-06-08',
  },
];

// ===== 목업 후기 데이터 =====
export const MOCK_REVIEWS: Review[] = [
  {
    id: 'review-001',
    shopId: 'shop-001',
    shopName: '강남 힐링스파',
    authorName: '김**',
    rating: 5,
    content: '정말 최고였어요! 테라피스트 선생님이 굉장히 전문적이셨고, 시설도 청결하고 쾌적했습니다. 다음에 또 방문할게요.',
    createdAt: '2024-05-20',
  },
  {
    id: 'review-002',
    shopId: 'shop-001',
    shopName: '강남 힐링스파',
    authorName: '이**',
    rating: 5,
    content: '어깨와 허리 통증이 심했는데 1시간 받고 나서 한결 나아진 느낌입니다. 가격 대비 최고입니다.',
    createdAt: '2024-05-18',
  },
  {
    id: 'review-003',
    shopId: 'shop-002',
    shopName: '홍대 아로마테라피',
    authorName: '박**',
    rating: 4,
    content: '향이 너무 좋아서 힐링이 됐어요. 공간도 예쁘고 분위기가 좋습니다. 다만 주차가 좀 불편했어요.',
    createdAt: '2024-05-15',
  },
];

// ===== 목업 공지사항 =====
export const MOCK_NOTICES: Notice[] = [
  {
    id: 'notice-001',
    title: '🎉 서비스 오픈을 축하합니다!',
    content: '안녕하세요. 지역/테마별 제휴업소 플랫폼이 정식 오픈하였습니다. 더 많은 제휴업소들이 입점할 예정이니 많은 관심 부탁드립니다.',
    isPinned: true,
    createdAt: '2024-06-01',
  },
  {
    id: 'notice-002',
    title: '제휴업소 입점 안내',
    content: '제휴업소 입점을 원하시는 업체는 고객센터 Q&A 게시판을 통해 문의해 주세요.',
    isPinned: false,
    createdAt: '2024-06-02',
  },
];

// ===== 목업 Q&A =====
export const MOCK_QNA: QnA[] = [
  {
    id: 'qna-001',
    question: '제휴업소 입점은 어떻게 신청하나요?',
    answer: '고객센터 Q&A를 통해 업체명, 지역, 연락처를 남겨주시면 1~2일 내 담당자가 연락드립니다.',
    authorName: '방문자',
    isAnswered: true,
    createdAt: '2024-06-03',
  },
  {
    id: 'qna-002',
    question: '예약은 어떻게 하나요?',
    answer: '각 업소 상세 페이지의 전화번호로 직접 연락하시거나 카카오톡 채널을 통해 예약하실 수 있습니다.',
    authorName: '홍길동',
    isAnswered: true,
    createdAt: '2024-06-04',
  },
  {
    id: 'qna-003',
    shopId: 'shop-001',
    question: '강남 힐링스파 주말 예약 가능한가요?',
    authorName: '방문예정',
    isAnswered: false,
    createdAt: '2024-06-05',
  },
];
