import { Notice, QnA, Review, Shop, User } from '@/lib/types';

export type SeedUser = User & {
  password: string;
};

export const seedUsers: SeedUser[] = [
  {
    id: 'admin',
    email: 'admin@massage.local',
    password: 'admin1234',
    name: 'Admin',
    role: 'ADMIN',
    status: 'approved',
  },
  {
    id: 'owner-001',
    email: 'owner@massage.local',
    password: 'owner1234',
    name: 'Owner',
    role: 'OWNER',
    managedShopId: 'shop-001',
    status: 'approved',
    businessName: 'Healing Spa',
    businessNumber: '123-45-67890',
    phone: '010-1111-2222',
  },
  {
    id: 'user-001',
    email: 'user@massage.local',
    password: 'user1234',
    name: 'User',
    role: 'USER',
    status: 'approved',
  },
  {
    id: 'owner-pending-001',
    email: 'pending-owner@massage.local',
    password: 'pending1234',
    name: 'Pending Owner',
    role: 'OWNER',
    status: 'pending',
    businessName: 'Pending Body Care',
    businessNumber: '222-33-44444',
    phone: '010-3333-4444',
  },
];

export const seedShops: Shop[] = [
  {
    id: 'shop-001',
    name: 'Healing Spa Seoul',
    slug: 'healing-spa-seoul',
    region: 'seoul',
    regionLabel: 'Seoul',
    subRegion: 'gangnam',
    subRegionLabel: 'Gangnam',
    theme: 'swedish',
    themeLabel: 'Swedish',
    isPremium: true,
    premiumOrder: 1,
    thumbnailUrl: '/images/shop1-thumb.jpg',
    bannerUrl: '/images/shop1-banner.jpg',
    images: ['/images/shop1-1.jpg', '/images/shop1-2.jpg'],
    tagline: 'Premium massage in central Seoul',
    description: 'A premium Swedish massage shop used as backend sample data.',
    address: '123 Gangnam-daero, Seoul',
    phone: '010-1234-5678',
    hours: '10:00 - 23:00',
    rating: 4.8,
    reviewCount: 2,
    courses: [
      { name: 'Basic Swedish', duration: '60 min', price: '70,000 KRW', description: 'Full body relief course' },
      { name: 'Premium Swedish', duration: '90 min', price: '100,000 KRW', description: 'Premium aromatherapy add-on' },
    ],
    tags: ['premium', 'parking', 'card'],
    isVisible: true,
    ownerId: 'owner-001',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'shop-002',
    name: 'Aroma Balance Hongdae',
    slug: 'aroma-balance-hongdae',
    region: 'seoul',
    regionLabel: 'Seoul',
    subRegion: 'mapo',
    subRegionLabel: 'Mapo',
    theme: 'aroma',
    themeLabel: 'Aroma',
    isPremium: true,
    premiumOrder: 2,
    thumbnailUrl: '/images/shop2-thumb.jpg',
    bannerUrl: '/images/shop2-banner.jpg',
    images: ['/images/shop2-1.jpg'],
    tagline: 'Calm aroma therapy for busy nights',
    description: 'Focused aroma therapy with a quiet and simple interior.',
    address: '45 Wausan-ro, Seoul',
    phone: '010-2345-6789',
    hours: '11:00 - 22:00',
    rating: 4.7,
    reviewCount: 1,
    courses: [
      { name: 'Aroma Relief', duration: '60 min', price: '65,000 KRW' },
      { name: 'Aroma Deep Care', duration: '90 min', price: '95,000 KRW' },
    ],
    tags: ['aroma', 'reservation', 'card'],
    isVisible: true,
    createdAt: '2024-02-01',
    updatedAt: '2024-06-02',
  },
  {
    id: 'shop-003',
    name: 'Busan Thai Stretch',
    slug: 'busan-thai-stretch',
    region: 'busan',
    regionLabel: 'Busan',
    subRegion: 'haeundae',
    subRegionLabel: 'Haeundae',
    theme: 'thai',
    themeLabel: 'Thai',
    isPremium: false,
    thumbnailUrl: '/images/shop3-thumb.jpg',
    bannerUrl: '/images/shop3-banner.jpg',
    images: ['/images/shop3-1.jpg'],
    tagline: 'Traditional Thai stretch and recovery',
    description: 'A sample Thai massage shop for shop list and detail routes.',
    address: '200 Haeundae-ro, Busan',
    phone: '010-3456-7890',
    hours: '09:00 - 24:00',
    rating: 4.9,
    reviewCount: 0,
    courses: [
      { name: 'Thai Basic', duration: '60 min', price: '55,000 KRW' },
      { name: 'Thai Long Course', duration: '120 min', price: '100,000 KRW' },
    ],
    tags: ['thai', 'stretch', 'couple'],
    isVisible: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-06-03',
  },
];

export const seedReviews: Review[] = [
  {
    id: 'review-001',
    shopId: 'shop-001',
    shopName: 'Healing Spa Seoul',
    authorName: 'Kim**',
    rating: 5,
    content: 'Very clean shop and consistent service quality.',
    createdAt: '2024-05-20',
  },
  {
    id: 'review-002',
    shopId: 'shop-001',
    shopName: 'Healing Spa Seoul',
    authorName: 'Lee**',
    rating: 5,
    content: 'Strong pressure control and friendly staff.',
    createdAt: '2024-05-18',
  },
  {
    id: 'review-003',
    shopId: 'shop-002',
    shopName: 'Aroma Balance Hongdae',
    authorName: 'Park**',
    rating: 4,
    content: 'Comfortable atmosphere, easy to relax.',
    createdAt: '2024-05-15',
  },
];

export const seedNotices: Notice[] = [
  {
    id: 'notice-001',
    title: 'Platform launch notice',
    content: 'Initial notice seeded for admin and board integration.',
    isPinned: true,
    createdAt: '2024-06-01',
  },
];

export const seedQna: QnA[] = [
  {
    id: 'qna-001',
    question: 'How do I request owner registration?',
    answer: 'Use the owner sign-up page and wait for admin approval.',
    authorName: 'Visitor',
    isAnswered: true,
    createdAt: '2024-06-03',
  },
  {
    id: 'qna-002',
    shopId: 'shop-001',
    question: 'Can I reserve for the weekend?',
    authorName: 'Guest',
    isAnswered: false,
    createdAt: '2024-06-05',
  },
];
